import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createSignerAdapter, parseLeaseUuid } from '@manifest-network/manifest-sdk';
import { createAuthTokens } from '@manifest-network/manifest-sdk/deploy';
import { makeSignDoc } from 'cosmjs-proto-signing-modern';
import { AuthInfo, TxBody } from 'cosmjs-types/cosmos/tx/v1beta1/tx.js';
import { createKeyringWalletProvider, type KeyringWalletOptions } from './keyring-wallet.js';

// This command is deliberately fixed to the PUBLIC fixture generated by the Go
// test. It cannot select a production key, backend, address, or chain.
const address = 'manifest19rl4cm2hmr8afy4kldpxz3fka4jguq0aaz02ta';
// Synthetic, valid bech32 address of twenty 0x01 bytes; no wallet corresponds to it.
const otherAddress = 'manifest1qyqszqgpqyqszqgpqyqszqgpqyqszqgpn3rfe5';
const chainId = 'manifest-ledger-testnet';
const directory = resolve('.local/mainnet');
const helperPath = resolve(directory, 'bin/keyring-signer');
const fixture: KeyringWalletOptions = {
  helperPath, home: resolve(directory, 'keyring-signer-fixture'), keyringBackend: 'test',
  keyName: 'fixture', expectedAddress: address, chainId,
};

// The real helper must fail closed with its stable code, surfaced through the adapter.
async function expectHelperFailure(changes: Partial<KeyringWalletOptions>, code: string) {
  await assert.rejects(createKeyringWalletProvider({ ...fixture, ...changes }),
    (error: unknown) => error instanceof Error && error.message.includes(`(${code})`), code);
}

async function main() {
  if (process.argv.length !== 2) throw new Error('No command arguments are accepted.');
  await expectHelperFailure({ expectedAddress: otherAddress }, 'ADDRESS_MISMATCH');
  await expectHelperFailure({ home: resolve(directory, 'keyring-signer-missing') }, 'KEYRING_HOME_UNAVAILABLE');
  await expectHelperFailure({ keyringBackend: 'file' }, 'NONINTERACTIVE_UNLOCK_UNAVAILABLE');
  const wallet = await createKeyringWalletProvider(fixture);
  try {
    const signer = await wallet.getSigner();
    const body = TxBody.encode(TxBody.fromPartial({ memo: 'Public disposable fixture; never broadcast' })).finish();
    const authInfo = AuthInfo.encode(AuthInfo.fromPartial({ fee: { amount: [], gasLimit: 1n } })).finish();
    const document = makeSignDoc(body, authInfo, chainId, 7);
    const result = await signer.signDirect(address, document);
    assert.deepEqual(result.signed, document);
    // The wrapper independently verifies each native signature with OpenSSL.
    assert.equal(Buffer.from(result.signature.signature, 'base64').length, 64);
    const tokens = createAuthTokens(createSignerAdapter(wallet), { chainId });
    const lease = parseLeaseUuid('11111111-1111-4111-8111-111111111111');
    const generic = await tokens.getAuthToken(lease);
    const payload = await tokens.getLeaseDataAuthToken(lease, 'a'.repeat(64));
    for (const token of [generic, payload]) {
      const decoded = JSON.parse(Buffer.from(token, 'base64').toString('utf8'));
      assert.equal(decoded.tenant, address);
      assert.equal(decoded.lease_uuid, lease);
      assert.equal(Buffer.from(decoded.signature, 'base64').length, 64);
    }
    // Neither challenge, token, nor signature is saved or printed.
    const report = {
      checkedAt: new Date().toISOString(), status: 'passed', fixtureAddress: address,
      helperSha256: createHash('sha256').update(await readFile(helperPath)).digest('hex'),
      verified: ['native SIGN_MODE_DIRECT', 'published SDK generic provider token', 'published SDK manifest-bound provider token', 'independent Node/OpenSSL signature verification',
        'native failure codes ADDRESS_MISMATCH, KEYRING_HOME_UNAVAILABLE and NONINTERACTIVE_UNLOCK_UNAVAILABLE'],
      productionKeyringAccessed: false, networkRequests: false, broadcast: false,
      tokensOrSignaturesPersisted: false,
    };
    await mkdir(directory, { recursive: true, mode: 0o700 });
    const destination = resolve(directory, 'keyring-fixture-check.json');
    const temporary = `${destination}.${process.pid}.tmp`;
    await writeFile(temporary, JSON.stringify(report, null, 2) + '\n', { mode: 0o600, flag: 'wx' });
    await rename(temporary, destination);
    console.log(JSON.stringify(report, null, 2));
  } finally { await wallet.disconnect(); }
}

main().catch(() => {
  console.error(JSON.stringify({ error: 'native_fixture_check_failed' }));
  process.exitCode = 1;
});
